import Head from 'next/head'
import { Container, Heading } from '@chakra-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>User management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="2xl" bg="whiteAlpha.300" paddingTop={'16'} centerContent>
        <Heading as="h2" size="2xl">User management</Heading>
      </Container>
    </>
  )
}
